apiVersion: v1
kind: Pod
metadata:
  name: qos-demo-4
  namespace: demo
spec:
  containers:

  - name: qos-demo-4-ctr-1
    image: nginx
    resources:
      requests:
        memory: "200Mi"
      limits:
        memory: "200Mi"
        cpu: "700m"

  - name: qos-demo-4-ctr-2
    image: redis

